CaseAFS/Controllers/TranslationController.cs
using CaseAFS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CaseAFS.Controllers
{
    [Authorize(Roles="Member, Admin")]
    public class TranslationController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            Translate translate = new Translate();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://api.funtranslations.com/translate/pirate?text=hi"))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    translate = JsonConvert.DeserializeObject<Translate>(apiResponse);
                }
            }
            return View(translate);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string Text)
        {
            Translate translate = new Translate();
            using (var httpClient = new HttpClient())
            {
                string apiurl = "http://api.funtranslations.com/translate/pirate?text=" + Text;
                using (var response = await httpClient.GetAsync(apiurl))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    translate = JsonConvert.DeserializeObject<Translate>(apiResponse);
                }
            }
            return View(translate);
        }
    }
}

CaseAFS/Controllers/UserController.cs
using CaseAFS.DataAccess;
using CaseAFS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq; 
namespace CaseAFS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private readonly CaseAfsDbContext _caseAfsDbContext;

        public UserController(CaseAfsDbContext caseAfsDbContext)
        {
            _caseAfsDbContext = caseAfsDbContext;
        }
        public IActionResult Index()
        {
                var result = from user in _caseAfsDbContext.Users
                             from role in _caseAfsDbContext.Roles.Where(r => r.RoleId == user.RoleId).ToList()
                             select new User()
                             {
                                 UserId = user.UserId,
                                 RoleId = role.RoleId,
                                 Email = user.Email,
                                 FirstName = user.FirstName,
                                 LastName = user.LastName,
                                 Password = user.Password,
                                 PasswordRepeat = user.PasswordRepeat,
                                 PhoneNumber = user.PhoneNumber,
                                 Role =(role == null)?null: new Role()
                                 {
                                     RoleId = role.RoleId,
                                     RoleName = role.RoleName
                                 }
                             };
                return View(result.ToList());
        }
    }
}

CaseAFS/Views/Shared/_Footer.cshtml
<footer class="border-top footer text-muted">
	<div class="container">
		&copy; 2022 - CaseAFS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
	</div>
</footer>

CaseAFS/Views/Shared/_Layout.cshtml
@using CaseAFS.Models

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - AFS Case </title>
	<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
	<link rel="stylesheet" href="~/css/site.css" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.2/font/bootstrap-icons.css">
	<link rel="stylesheet" href="https://cdn.datatables.net/1.12.0/css/jquery.dataTables.min.css">

</head>
<body>
	<header>
		<div class="container">
			<br />
			<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-black border-bottom box-shadow mb-3">
				<div class="container">
					<a class="navbar-brand" asp-controller="Home" asp-action="Index">
						<img src="~/images/image/logo-small.png" />
						<b>AFS</b><span style="color: green"><b>Case</b></span>
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
							aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
						<ul class="navbar-nav flex-grow-1" style="width:auto;">
							<li class="nav-item">
								<a class="nav-link text-white" asp-action="Index" asp-controller="Translation">Translation</a>
							</li>
								<li class="nav-item">
									<a class="nav-link text-white" asp-action="Index" asp-controller="User">
										Users
									</a>
								</li>
							<li class="nav-item">
								<a class="nav-link text-white" asp-action="Register" asp-controller="Account">
									Register
								</a>
							</li>
						</ul>
						<ul class="navbar-nav " >
							<li class="nav-item">
								<a class="nav-link text-white" asp-action="Index" asp-controller="Account">
									<i class="bi bi-box-arrow-in-left"></i> Login
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link text-white me-0" asp-action="Logout" asp-controller="Account">
									<i class="bi bi-box-arrow-in-right"></i> Log Out
								</a>
							</li>
						</ul>
					</div>
				</div>
			</nav>
		</div>

	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

@*	<footer class="border-top footer text-muted">
		<div class="container">
			&copy; 2022 - CaseAFS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
		</div>
	</footer>*@
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
	<script src="//cdn.datatables.net/1.12.0/js/jquery.dataTables.min.js"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>